backend:
  name: github
  repo: mwehnert/bakingbread
  branch: main
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    slug: index
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    extension: mdx
    format: frontmatter
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "Feature", name: "feature", widget: "image" }
          - {
              label: "Credit",
              name: "credit",
              widget: "string",
              required: false,
            }
          - {
              label: "Credit-Link",
              name: "creditlink",
              widget: "string",
              required: false,
            }
      - label: "Steps"
        name: "steps"
        widget: "list"
        required: false
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - {
              label: "Amount",
              name: "amount",
              widget: "number",
              required: false,
            }
          - { label: "Unit", name: "unit", widget: "string", required: false }
          - { label: "Step", name: "step", widget: "number", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
